### ISSUE TITLE
easybup seems dead/unavailable

### ISSUE THREAD

**Issue by tst2005** [bup/bup.github.io#1]
On https://bup.github.io/ we can read 

```
easybup
    A script that uses Fabric and a configuration file to run backups for multiple machines
    in parallel. The script can be configured to "rotate" backups (e.g. archive current bup
    repository and create a new one) in order to keep only a maximum of either 15 days
    or two months.
```

The link on [easybup](https://github.com/AnoopAlias/easybup) is dead. The easybup seems not availavle anymore.

**Comment by douglasmiranda** [comment]
I was very interested in the easybup, since what I'm doing here from scratch is basically what easybup was.

**Comment by lelutin** [comment]
I've removed the related project from the web site since the repository has completely disappeared and I couldn't find any fork of it.
